//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExGrouping
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Nb { get; set; }
        public string Name { get; set; }
        public string Firstname { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Address { get; set; }
        public string ZIP { get; set; }
        public string City { get; set; }
    }
}
